name: evening_update_and_render_graph

on:
  schedule:
    # Weekdays at 22:30 UTC (6:30pm EDT / 5:30pm EST) after market close
    - cron: "30 22 * * 1-5
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (with LFS)
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Pull LFS files
        run: git lfs pull

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Fill actuals and rebuild page
        run: python scripts/update_and_render_graph.py

      - name: Commit and push site
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/history.csv docs/index.html
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Update actuals: $(date -u +"%Y-%m-%d %H:%M UTC")"
            git push
          fi
