name: daily-predictions

on:
  schedule:
    # Weekdays at 12:00 UTC (8am EDT / 7am EST)
    - cron: "0 12 * * 1-5"
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (with LFS)
        uses: actions/checkout@v4
        with:
          lfs: true
          fetch-depth: 0

      - name: Pull LFS files
        run: git lfs pull

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run predictions (both students)
        run: python scripts/dqn_model_testing_runner.py

      - name: Commit and push site
        run: |
          # identity
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git config --global --add safe.directory "$GITHUB_WORKSPACE"

          # always rebase when pulling, and auto-stash local changes if any
          git config pull.rebase true
          git config rebase.autoStash true

          # 1) pull first (clean index), then stage & commit
          git fetch origin
          git pull --rebase

          # 2) stage generated files
          git add docs/history.csv docs/index.html

          # 3) commit only if there are staged changes
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Update actuals: $(date -u +"%Y-%m-%d %H:%M UTC")"
            git push
          fi